name: CI

on:
    pull_request:
    push:
        branches:
            - 'develop'
        tags:
            - "*.*.*"

env:
    IMAGE: ${{ vars.NCR_REGISTRY }}/we-meet
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/we-meet:latest

jobs:
    lint:
        name: Check lint (black)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11' 
            - name: install black
              run: pip install black
            - name: check black
              run: black --check .

    build:
        needs: lint
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: test
              run: |
                docker-compose -f docker-compose-test.yml up --build -d
                docker-compose -f docker-compose-test.yml run web python manage.py test

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Get current timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: Get version
              if: startsWith(github.ref, 'refs/tags')
              id: version
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

            - name: build-and-push
              if: startsWith(github.ref, 'refs/heads')
              uses: docker/build-push-action@v4
              with:
                context: meet
                tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                push: true

            - name: build-and-push
              if: startsWith(github.ref, 'refs/tags')
              uses: docker/build-push-action@v4
              with:
                context: meet
                tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.version.outputs.VERSION }}"
                push: true
